### ISSUE TITLE
Start with Individual Unit Convert Methods?

### ISSUE THREAD

**Issue by hartkemd** [pjlplourde/UnitConversionApp#3]
I wonder if we should start small - with individual Length Convert methods, like "ConvertMetresToFeet()", or something like that, and then make the code more DRY later on. That would give us something to start with and start testing. What do you think? Or, did you have something more in mind with the Convert method? I'm not as familiar with generics, so there might be something I'm missing.

**Comment by SteveTeece** [comment]
Personally I've found it doesn't really matter how 'dirty' or not-dry the starting code is.  I think it is better to get a starting point with a few simple methods that work, then clean up later in a refactor.  As you go, you will find better ways to do things, and identify code that needs to be refactored, or sometimes an entire change in the design because of a complication you had not considered.

**Comment by hartkemd** [comment]
I found a way to make a method that converts one unit of length to other units. I'm sure it's not perfect, but it's something to start with. I also re-wired some of the UI that I did before. I'll make a pull request in a minute.

**Comment by pjlplourde** [comment]
Hi @hartkemd , I'll have a look at your 2 pull requests shortly, and thank you for the contributions.  The UnitConverter.Convert uses generics to be the one-stop-shop triage method which then will go into the specific methods to convert length, mass, temperature, etc.  This isn't just about DRY, it's also about the Single Responsibility Principle and about scalability to add other unit types later.  While I agree with @SteveTeece about starting dirty to get going, when you know where you are going, there is nothing wrong with executing that in a way that will make refactoring harder later.
